services:
  - name: laravel-app
    type: web
    env: docker
    plan: free
    autoDeploy: true
    repo: https://github.com/nathan2002-hash/venusnapback
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:MWUwaThUezip3y/E/igwnzw/jVw0PgWNbYGpFi0Lv90=
      - key: APP_DEBUG
        value: false
      - key: PORT
        value: 8000
    disk:
      name: storage
      mountPath: /var/www/html/storage
